### ISSUE TITLE
Export failes if the message is in cp932

### ISSUE THREAD

**Issue by k4200** [k4200/openmailarchiva-server#15]
```
DEBUG 3/17 09:18:16 - extracted message
{uniqueId='349d0a96bebdac4f3301d948c7380387689e53e7',
volumepath='/var/store/store23',indexpath='/var/index/index23',volumestatus='ACTIVE',closedDate='null',createdDate='Fri
Feb 19 12:59:42 JST 2016',from='foo@example.jp
<foo@example.jp>',to='<bar@example.com>',priority='3',subject='important email blah blah',deliveredto='mailarchive@example.com',attach='0',size='13.05',sentdate='d20160315202828',archivedate='d20160315202830',receiveddate='d20160315202830'}
DEBUG 3/17 09:18:16 - cp932
java.io.UnsupportedEncodingException: cp932
    at sun.nio.cs.StreamDecoder.forInputStreamReader(Unknown Source)
    at java.io.InputStreamReader.<init>(Unknown Source)
    at com.sun.mail.handlers.text_plain.getContent(text_plain.java:90)
    at javax.activation.DataSourceDataContentHandler.getContent(Unknown Source)
    at javax.activation.DataHandler.getContent(Unknown Source)
    at javax.mail.internet.MimeBodyPart.getContent(MimeBodyPart.java:630)
    at com.stimulus.archiva.extraction.MessageExtraction.dumpPart(MessageExtraction.java:127)
    at com.stimulus.archiva.extraction.MessageExtraction.dumpPart(MessageExtraction.java:135)
    at com.stimulus.archiva.extraction.MessageExtraction.extractMessage(MessageExtraction.java:72)
    at com.stimulus.archiva.extraction.MessageExtraction.<init>(MessageExtraction.java:53)
    at com.stimulus.archiva.service.MessageService.extractMessage(MessageService.java:539)
    at com.stimulus.archiva.presentation.MessageBean.viewMessage(MessageBean.java:148)
    at com.stimulus.archiva.presentation.MessageBean.viewmail(MessageBean.java:131)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.stimulus.struts.BeanAction.callMethod(BeanAction.java:150)
    at com.stimulus.struts.BeanAction.execute(BeanAction.java:176)
    at org.apache.struts.chain.commands.servlet.ExecuteAction.execute(ExecuteAction.java:58)
    at org.apache.struts.chain.commands.AbstractExecuteAction.execute(AbstractExecuteAction.java:67)
    at org.apache.struts.chain.commands.ActionCommandBase.execute(ActionCommandBase.java:51)
    at org.apache.commons.chain.impl.ChainBase.execute(ChainBase.java:190)
    at org.apache.commons.chain.generic.LookupCommand.execute(LookupCommand.java:304)
    at org.apache.commons.chain.impl.ChainBase.execute(ChainBase.java:190)
    at org.apache.struts.chain.ComposableRequestProcessor.process(ComposableRequestProcessor.java:283)
    at org.apache.struts.action.ActionServlet.process(ActionServlet.java:1913)
    at org.apache.struts.action.ActionServlet.doGet(ActionServlet.java:449)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:617)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at com.stimulus.util.UTF8Filter.doFilter(UTF8Filter.java:33)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.securityfilter.filter.SecurityFilter.doFilter(SecurityFilter.java:231)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:433)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:128)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:286)
    at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:845)
    at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:583)
    at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:447)
    at java.lang.Thread.run(Unknown Source)

**Comment by k4200** [comment]
Link to the official information:
http://www.oracle.com/technetwork/java/javamail/faq/index.html#unsupen

**Comment by k4200** [comment]
Fixed
